frontend:
  - changed-files:
    - any-glob-to-any-file:
      - src/*

prisma:
  - changed-files:
    - any-glob-to-any-file:
      - prisma/*

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
