services:
  dev-db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: nusc
    networks:
      - nusc
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:

networks:
  nusc:
